# Generated by Django 2.0.4 on 2018-06-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacriteria',
            name='acronym',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
