# Generated by Django 2.0.4 on 2018-05-19 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=3, unique=True)),
                ('metric', models.CharField(max_length=12)),
                ('atribute', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Heuristic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acronym', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('browser', models.CharField(max_length=20)),
                ('browser_version', models.CharField(max_length=10)),
                ('review', models.TextField()),
                ('username_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user')),
                ('website_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Website')),
            ],
        ),
        migrations.AddField(
            model_name='heuristic',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Review'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='heuristic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Heuristic'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('website_id', 'username_id')},
        ),
    ]
