# Generated by Django 2.0.4 on 2018-06-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metacriteria',
            name='metric',
        ),
    ]
