# Generated by Django 2.0.4 on 2018-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaheuristic',
            name='acronym',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
