# Generated by Django 2.0.4 on 2018-06-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180604_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacriteria',
            name='relevance',
            field=models.CharField(default='CR CR CR CR CR CR CR CR CR CR CR CR CR CR CR CR CR', max_length=55),
        ),
        migrations.AddField(
            model_name='metaheuristic',
            name='relevance',
            field=models.CharField(default='4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4', max_length=35),
        ),
        migrations.AddField(
            model_name='review',
            name='UP',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='website',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
