# Generated by Django 2.0.4 on 2018-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_website_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacriteria',
            name='relevance',
            field=models.CharField(default='CR CR CR CR CR CR CR CR CR CR CR CR CR CR CR CR CR', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metaheuristic',
            name='relevance',
            field=models.CharField(default='4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4', max_length=35),
            preserve_default=False,
        ),
    ]
