# Generated by Django 2.0.4 on 2018-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180605_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='UP',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
