# Generated by Django 2.0.4 on 2018-06-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_review_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='UP',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
