# Generated by Django 2.0.4 on 2018-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180605_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacriteria',
            name='relevance',
            field=models.CharField(default='CR CR CR CR CR CR CR CR CR CR CR CR CR CR CR CR CR', max_length=55),
        ),
        migrations.AlterField(
            model_name='metaheuristic',
            name='relevance',
            field=models.CharField(default='4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4_4', max_length=35),
        ),
        migrations.AlterField(
            model_name='review',
            name='UP',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='website',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
